config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
  root to: 'pages#home'
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_sh'
  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
enum status: { draft: 0 , published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body

   belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
has_many :technologies
accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
 include Placeholder
  validates_presence_of :title, :body , :main_image, :thumb_image
  def self.angular
    where(subtitle: "Angular")
end


scope :ruby_on_rails , -> {where(subtitle: "Ruby on Rails")}
after_initialize :set_defaults


 def set_defaults
   self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
   self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
 end
end

app/models/skill.rb
class Skill < ApplicationRecord
 include Placeholder
    validates_presence_of :title , :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_path(@blog), notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def toggle_status
   if  @blog.draft?
     @blog.published!
   elsif @blog.published?
     @blog.draft!
   end

   redirect_to blogs_url, notice: 'Blog post status was updated.'
 end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts= Blog.all
    @skills= Skill.all

  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  def index
    @portfolio_items= Portfolio.all

  end
  def angular
    @angular_portfolio_items= Portfolio.angular
  end
  def new

    @portfolio_item = Portfolio.new
     3.times { @portfolio_item.technologies.build }
  end
  def create
    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

   def show
   end
   def edit

    end
    def destroy
      @portfolio_item.destroy
      respond_to do |format|
        format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def update


      respond_to do |format|
        if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
          format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
    def set_portfolio
      @portfolio_item = Portfolio.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title.upcase %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center><%= yield %></center>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<center><h1>Page home</h1></center>

<h1>Blog posts</h1>

<%= @posts.inspect %>


<h1>Skills</h1>


<%= @skills.inspect %>

app/views/portfolios/angular.html.erb
<p id="notice"><%= notice %></p>
<center>
        <h1> Angular Portfolio items</h1>
                                </center>
 <%=  link_to "create a New portfolio" , new_portfolio_url %>
    <% @angular_portfolio_items.each do |p| %>
          <p><%=  link_to p.title , portfolio_sh_path(p) %> </p>
          <p><%= p.subtitle %> </p>
          <p><%= p.body %> </p>
          <p><%= image_tag p.thumb_image unless p.thumb_image.nil? %> </p>
          <%= link_to "Edit", edit_portfolio_path(p) %>

          <br>
          <%= link_to 'Destroy', p , method: :delete, data: { confirm: 'Are you sure?' } %>
          <hr>

    <% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>
<center>
        <h1>Portfolio items</h1>
                                </center>
 <%=  link_to "create a New portfolio" , new_portfolio_url %>
    <% @portfolio_items.each do |p| %>
          <p><%=  link_to p.title , portfolio_sh_path(p) %> </p>
          <p><%= p.subtitle %> </p>
          <p><%= p.body %> </p>
          <p><%= image_tag p.thumb_image unless p.thumb_image.nil? %> </p>
          <%= link_to "Edit", edit_portfolio_path(p) %>

          <br>
          <%= link_to 'Destroy', p , method: :delete, data: { confirm: 'Are you sure?' } %>
          <hr>

    <% end %>

app/views/portfolios/new.html.erb
<center><h1>Create a new Portfolio Item</h1></center>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <ul>
    <%= f.fields_for :technologies do |technology_form| %>

        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
  
    <% end %>
  </ul>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<h2><em><%= @portfolio_item.subtitle %></em> </h2>

<p><%= @portfolio_item.body %></p>

<h2>Technologies Used:</h2>

<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>